// shChapters.js — pt-BR names for the 97 Harmonized System / NCM CHAPTERS (SH2, the
// 2-digit code prefix).
//
// Consumed by the FilterMenu product tree (multi-tree NCM/HS pickers) to label the SH2
// parent nodes readably — "44 · Madeira e carvão vegetal" instead of a bare "44". Only
// SH2 gets a name: its dictionary is small (97 chapters) and stable (the HS chapter
// structure changes rarely). SH4 headings (~1200) and SH6 subheadings (~5000) are far
// too many to keep as a hand-maintained reference, so those deeper parent nodes stay as
// bare codes and rely on the leaf descriptions the snapshot already carries.
//
// Names are the standard Brazilian NCM chapter titles, trimmed to the leading phrase so
// the picker label stays compact (the tree row also carries the full title in `title`).
// This is end-user-facing reference data → Portuguese (project language rule).
window.SH_CHAPTERS = {
  '01': 'Animais vivos',
  '02': 'Carnes e miudezas comestíveis',
  '03': 'Peixes, crustáceos e moluscos',
  '04': 'Leite, laticínios, ovos e mel',
  '05': 'Outros produtos de origem animal',
  '06': 'Plantas vivas e floricultura',
  '07': 'Produtos hortícolas, raízes e tubérculos',
  '08': 'Frutas; cascas de cítricos e melões',
  '09': 'Café, chá, mate e especiarias',
  '10': 'Cereais',
  '11': 'Produtos de moagem; amidos e féculas',
  '12': 'Sementes e frutos oleaginosos; grãos e plantas industriais',
  '13': 'Gomas, resinas e extratos vegetais',
  '14': 'Matérias para entrançar e outros produtos vegetais',
  '15': 'Gorduras e óleos animais ou vegetais',
  '16': 'Preparações de carne, peixes ou crustáceos',
  '17': 'Açúcares e produtos de confeitaria',
  '18': 'Cacau e suas preparações',
  '19': 'Preparações à base de cereais, farinhas e leite',
  '20': 'Preparações de hortícolas e frutas',
  '21': 'Preparações alimentícias diversas',
  '22': 'Bebidas, líquidos alcoólicos e vinagres',
  '23': 'Resíduos alimentares; rações para animais',
  '24': 'Fumo (tabaco) e seus sucedâneos',
  '25': 'Sal; enxofre; terras, pedras, gesso e cimento',
  '26': 'Minérios, escórias e cinzas',
  '27': 'Combustíveis e óleos minerais',
  '28': 'Produtos químicos inorgânicos',
  '29': 'Produtos químicos orgânicos',
  '30': 'Produtos farmacêuticos',
  '31': 'Adubos (fertilizantes)',
  '32': 'Extratos tanantes/tintoriais; tintas e vernizes',
  '33': 'Óleos essenciais; perfumaria e cosméticos',
  '34': 'Sabões, ceras, velas e produtos de limpeza',
  '35': 'Matérias albuminoides; colas e enzimas',
  '36': 'Pólvoras, explosivos e artigos de pirotecnia',
  '37': 'Produtos para fotografia e cinematografia',
  '38': 'Produtos diversos das indústrias químicas',
  '39': 'Plásticos e suas obras',
  '40': 'Borracha e suas obras',
  '41': 'Peles e couros',
  '42': 'Obras de couro; artigos de viagem e bolsas',
  '43': 'Peles com pelo e suas obras',
  '44': 'Madeira, carvão vegetal e obras de madeira',
  '45': 'Cortiça e suas obras',
  '46': 'Obras de espartaria ou de cestaria',
  '47': 'Pastas de madeira; papel para reciclar',
  '48': 'Papel e cartão e suas obras',
  '49': 'Livros, jornais e produtos gráficos',
  '50': 'Seda',
  '51': 'Lã e pelos finos ou grosseiros',
  '52': 'Algodão',
  '53': 'Outras fibras têxteis vegetais',
  '54': 'Filamentos sintéticos ou artificiais',
  '55': 'Fibras sintéticas ou artificiais descontínuas',
  '56': 'Feltros, falsos tecidos, cordéis e cordas',
  '57': 'Tapetes e revestimentos têxteis para pavimentos',
  '58': 'Tecidos especiais, rendas e bordados',
  '59': 'Tecidos impregnados ou revestidos; usos técnicos',
  '60': 'Tecidos de malha',
  '61': 'Vestuário e acessórios, de malha',
  '62': 'Vestuário e acessórios, exceto de malha',
  '63': 'Outros artefatos têxteis; trapos',
  '64': 'Calçado, polainas e artefatos semelhantes',
  '65': 'Chapéus e artefatos semelhantes',
  '66': 'Guarda-chuvas, bengalas e chicotes',
  '67': 'Penas, penugem e flores artificiais',
  '68': 'Obras de pedra, gesso, cimento e semelhantes',
  '69': 'Produtos cerâmicos',
  '70': 'Vidro e suas obras',
  '71': 'Pérolas, pedras e metais preciosos; bijuterias',
  '72': 'Ferro fundido, ferro e aço',
  '73': 'Obras de ferro fundido, ferro ou aço',
  '74': 'Cobre e suas obras',
  '75': 'Níquel e suas obras',
  '76': 'Alumínio e suas obras',
  '78': 'Chumbo e suas obras',
  '79': 'Zinco e suas obras',
  '80': 'Estanho e suas obras',
  '81': 'Outros metais comuns e suas obras',
  '82': 'Ferramentas, cutelaria e talheres',
  '83': 'Obras diversas de metais comuns',
  '84': 'Reatores, caldeiras, máquinas e aparelhos mecânicos',
  '85': 'Máquinas e materiais elétricos',
  '86': 'Material para vias férreas',
  '87': 'Veículos terrestres (automóveis, tratores e outros)',
  '88': 'Aeronaves e aparelhos espaciais',
  '89': 'Embarcações e estruturas flutuantes',
  '90': 'Instrumentos de óptica, medida e precisão',
  '91': 'Aparelhos de relojoaria',
  '92': 'Instrumentos musicais',
  '93': 'Armas e munições',
  '94': 'Móveis, iluminação e construções pré-fabricadas',
  '95': 'Brinquedos, jogos e artigos de esporte',
  '96': 'Obras diversas',
  '97': 'Objetos de arte, de coleção ou antiguidades',
};
